### ISSUE TITLE
Printer names not clear!!

### ISSUE THREAD

**Issue by jundl77** [Lucas-Steinmann/atisprint#1]
The printer name:

- pool-sw1-raw
- pool-sw2-raw
- pool-sw3-raw

do not seem to work, at least the following command doesn't work:

``` . atisprint.sh printer_name doc_name ```

where printer_name is one of the above. 

I suggest you add the available printer names in the description. Alternatively you could replace printer_name with the parameters ```p1..p3``` for printer 1 to printer 3 and maybe ```pc``` for printer color. Something like that.

**Comment by Lucas-Steinmann** [comment]
The printer names from the output of `atisstat` should work.
For the output:
```
auskunft-sw1 accepting requests since Fri Aug 26 10:57:50 2016
pool-farb1 accepting requests since Tue Dec 20 16:20:51 2016
pool-sw1 accepting requests since Mon Jan 16 15:09:09 2017
pool-sw2 accepting requests since Tue Jan 17 18:45:40 2017
pool-sw3 accepting requests since Tue Jan 17 10:13:25 2017
```
the printer names in the first column should be valid printer names for printing with `atisprint`.

But thanks for the input I will add a small "guide" for using the scripts and think about the possibilities of increasing usability as you suggested.
